Repository quadraticvotingJP/quadratic-voting-jp, pull requests merged in 2022-05, with the labels that each got.

#170 remove functions
  firebase.json
  functions/.eslintrc.js
  functions/.gitignore
  functions/package-lock.json
  functions/package.json
  functions/src/index.ts
  functions/tsconfig.dev.json
  functions/tsconfig.json
Labels: enhancement, want

#176 feature issue#171 vercel research mori
  architecture/application/routing.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  pages/dashboard/[id].tsx
  pages/vote/[id].tsx
Labels: enhancement, must

#184 public配下の使用していないFileを削除 #174
  public/404.html
  public/favicon.ico
  public/index.html
  public/vercel.svg
Labels: enhancement

#185 i18nextの設定 #177
  architecture/application/postEvent.ts
  pages/dashboard/[id].tsx
  pages/vote/[id].tsx
Labels: bug, enhancement

#186 ルーティングの整備 #160
  architecture/application/dashboardData.ts
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcVoteForm.tsx
  pages/vote/[id].tsx
Labels: bug, must

#187 リンクの修正 #181
  architecture/application/postEvent.ts
  components/ecosystems/EcDashboard.tsx
  pages/dashboard/[id].tsx
  pages/vote/[id].tsx
Labels: bug, enhancement

#189 言語の修正 #188
  components/ecosystems/EcCreateForm.tsx
  next-i18next.config.js
  pages/dashboard/[id].tsx
  pages/vote/[id].tsx
Labels: bug, must

#198 renovatejsonの更新 #197
  renovate.json
Labels: enhancement

#201 renovatejsonの更新 #200
  renovate.json
Labels: bug

#210 configの変更 #199
  renovate.json
Labels: enhancement

#226 styleの変更 #164
  components/atoms/AtInputLabel.tsx
  components/atoms/AtInputLabelNoMark.tsx
  components/molecules/MoHeader.tsx
  pages/_app.tsx
Labels: enhancement

#233 Feature issue#180 change readme
  README.md
  components/atoms/AtButton.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcExplanation.tsx
  components/ecosystems/EcVoteForm.tsx
  components/molecules/MoButtons.tsx
  components/organisms/OrCardBar.tsx
  components/organisms/OrCardForms.tsx
  components/organisms/OrCardTextField.tsx
Labels: enhancement

#237 warnの修正 #182
  package-lock.json
  pages/vote/[id].tsx
  tailwind.config.js
Labels: bug

#245 MITLicenceの作成 #159
  LICENSE
  components/molecules/MoFooter.tsx
  public/locales/ja/common.json
Labels: enhancement

#246 styleの変更 #244
  README.md
  components/atoms/AtH2.tsx
  components/ecosystems/EcVoteForm.tsx
  components/molecules/MoFooter.tsx
  components/molecules/MoProcess.tsx
  pages/_app.tsx
  public/locales/ja/common.json
Labels: enhancement

#262 hostingの削除 #261
  firebase.json
Labels: enhancement

#265 Hotfixes #260
  pages/vote/[id].tsx
Labels: bug

#270 表示制御修正
  pages/vote/[id].tsx
Labels: bug

#271 release 1.0.1
  firebase.json
  pages/vote/[id].tsx
Labels: release

#275 Feature issue#273 change votes
  README.md
  architecture/application/dashboardData.ts
  components/ecosystems/EcDashboard.tsx
  components/molecules/MoLabelBar.tsx
  components/molecules/MoLabelForm.tsx
  components/organisms/OrCardBar.tsx
  components/organisms/OrCardForms.tsx
  components/organisms/OrCardProcess.tsx
  pages/_app.tsx
  public/locales/ja/common.json
  types/shared.d.ts
Labels: enhancement

#276 release 1.1.0
  README.md
  architecture/application/dashboardData.ts
  components/ecosystems/EcDashboard.tsx
  components/molecules/MoLabelBar.tsx
  components/molecules/MoLabelForm.tsx
  components/organisms/OrCardBar.tsx
  components/organisms/OrCardForms.tsx
  components/organisms/OrCardProcess.tsx
  pages/_app.tsx
  public/locales/ja/common.json
  types/shared.d.ts
Labels: release
