Repository quadraticvotingJP/quadratic-voting-jp, pull requests merged in 2022-06, with the labels that each got.

#248 GAの設置 #83
  lib/README.md
  lib/gtag.js
  pages/_app.tsx
  pages/_document.tsx
  tsconfig.json
Labels: enhancement

#284 google adsenceの追加 #65
  components/ecosystems/EcAdSense.tsx
  components/ecosystems/EcAdvertisement.tsx
  components/ecosystems/EntryPoint.tsx
  package.json
  pages/_app.tsx
  pages/_document.tsx
  types/shared.d.ts
  yarn.lock
Labels: enhancement

#285 release 1.4.0
  components/ecosystems/EcAdSense.tsx
  components/ecosystems/EcAdvertisement.tsx
  components/ecosystems/EntryPoint.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  types/shared.d.ts
  yarn.lock
Labels: release

#272 routing fix
  components/ecosystems/EcInvalidLink.tsx
  components/ecosystems/EcVoteForm.tsx
  components/ecosystems/EntryPoint.tsx
  pages/vote/[id].tsx
  public/locales/ja/common.json
Labels: release

#295 Hotfix#292 debug adsence
  components/molecules/MoFooter.tsx
  pages/_app.tsx
Labels: enhancement

#296 Release v1.5.1
  components/molecules/MoFooter.tsx
  pages/_app.tsx
Labels: release

#302 robottxtの作成 #281
  .eslintrc.json
  package-lock.json
  package.json
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  sitemap.config.js
  yarn.lock
Labels: enhancement

#303 v1.7.0
  .eslintrc.json
  package-lock.json
  package.json
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  sitemap.config.js
  yarn.lock
Labels: release

#312 Feature issue#311 add styled components
  package.json
  pages/_document.tsx
  yarn.lock
Labels: enhancement

#308 loading #268
  .babelrc
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcLoading.tsx
  components/ecosystems/EcVoteForm.tsx
  components/ecosystems/EntryPoint.tsx
  components/molecules/MoFooter.tsx
  components/molecules/MoHeader.tsx
  context/LoadingContext.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  yarn.lock
Labels: enhancement

#250 Feature issue#165 create lp
  architecture/adapter/getDocumentOnly.tsx
  architecture/adapter/getImagesList.ts
  architecture/application/getImages.ts
  architecture/application/getLpImages.tsx
  components/atoms/AtImage.tsx
  components/atoms/EntryPoint.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcExplanation.tsx
  components/ecosystems/EcLp.tsx
  components/ecosystems/EntryPoint.tsx
  firebase/initialize.js
  media.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  public/locales/ja/common.json
  types/shared.d.ts
  yarn.lock
Labels: enhancement

#322 v2.0.0
  architecture/adapter/getDocumentOnly.tsx
  architecture/adapter/getImagesList.ts
  architecture/application/getImages.ts
  architecture/application/getLpImages.tsx
  components/atoms/AtImage.tsx
  components/atoms/EntryPoint.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcExplanation.tsx
  components/ecosystems/EcLp.tsx
  components/ecosystems/EntryPoint.tsx
  firebase/initialize.js
  media.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  public/locales/ja/common.json
  types/shared.d.ts
  yarn.lock
Labels: release

#324 Feature issue#323 create privacy policy
  components/ecosystems/EcPrivacyPolicy.tsx
  components/ecosystems/EcTermsOfService.tsx
  components/ecosystems/EntryPoint.tsx
  components/molecules/MoFooter.tsx
  pages/privacypolicy/index.tsx
  pages/termsofservice/index.tsx
  public/locales/ja/common.json
Labels: enhancement, production

#325 v2.1.0
  components/ecosystems/EcPrivacyPolicy.tsx
  components/ecosystems/EcTermsOfService.tsx
  components/ecosystems/EntryPoint.tsx
  components/molecules/MoFooter.tsx
  pages/privacypolicy/index.tsx
  pages/termsofservice/index.tsx
  public/locales/ja/common.json
Labels: release

#327 リンクの変更 #326
  public/locales/ja/common.json
Labels: release

#328 v2.1.1
  public/locales/ja/common.json
Labels: release

#331 A8netの導入 #330
  components/ecosystems/EcAdSense.tsx
  next.config.js
  pages/_app.tsx
Labels: enhancement

#332 v2.2.1
  components/ecosystems/EcAdSense.tsx
  next.config.js
  pages/_app.tsx
Labels: release

#341 広告の再配置 #338
  components/ecosystems/EcAdSense.tsx
  next.config.js
  pages/_app.tsx
Labels: enhancement, production

#342 v2.3.1
  components/ecosystems/EcAdSense.tsx
  next.config.js
  pages/_app.tsx
Labels: release

#346 AtInputのMUIを剥がす #343
  components/atoms/AtBar/index.tsx
  components/atoms/AtImage/index.tsx
  components/atoms/AtInputLabel.tsx
  components/atoms/AtInputLabelNoMark.tsx
  components/atoms/AtLabel/index.tsx
  components/atoms/AtNoMarkLabel/index.tsx
  components/atoms/EntryPoint.tsx
  components/ecosystems/EcVoteForm.tsx
  components/molecules/EntryPoint.tsx
  components/molecules/MoLabelBar.tsx
  components/molecules/MoLabelBar/index.tsx
  components/molecules/MoLabelForm/index.tsx
  components/molecules/MoLabelText/index.tsx
  components/molecules/MoLabelTextField/index.tsx
  components/organisms/OrAccordion.tsx
  components/organisms/OrCardBar.tsx
  components/organisms/OrCardForm.tsx
  components/organisms/OrCardForms.tsx
  components/organisms/OrCardProcess.tsx
  components/organisms/OrCardText.tsx
  components/organisms/OrCardTextField.tsx
  components/organisms/OrVoteOptionCardForm.tsx
  styles/tailwind.css
Labels: enhancement, develop

#351 Feature issue#347 change directory
  components/atoms/AtH2.tsx
  components/atoms/AtHref.tsx
  components/atoms/AtHref/index.tsx
  components/atoms/EntryPoint.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcInvalidLink.tsx
  components/ecosystems/EcLp.tsx
  components/ecosystems/EcPrivacyPolicy.tsx
  components/ecosystems/EcTermsOfService.tsx
  components/ecosystems/EcVoteForm.tsx
  components/molecules/EntryPoint.tsx
  components/molecules/MoAccordion.tsx
  components/molecules/MoFooter/index.tsx
  components/molecules/MoHeader/index.tsx
  components/molecules/MoProcess.tsx
  components/molecules/MoProcess/index.tsx
Labels: enhancement

#352 Feature issue#348 change card
  components/organisms/EntryPoint.tsx
  components/organisms/OrAccordion/index.tsx
  components/organisms/OrCardBar/index.tsx
  components/organisms/OrCardForm/index.tsx
  components/organisms/OrCardForms/index.tsx
  components/organisms/OrCardProcess.tsx
  components/organisms/OrCardProcess/index.tsx
  components/organisms/OrCardText/index.tsx
  components/organisms/OrCardTextField/index.tsx
  components/organisms/OrProposalBlocks.tsx
  components/organisms/OrProposalBlocks/index.tsx
  components/organisms/OrVoteOptionCardForm/index.tsx
Labels: enhancement

#356 IconButtonをMuiから剥がす #355
  components/atoms/AtIconButton.tsx
  components/atoms/AtIconButton/index.tsx
  components/atoms/EntryPoint.tsx
  components/molecules/MoAccordion.tsx
  package.json
  yarn.lock
Labels: enhancement, develop

#357 Accordionのtailwindcssを剥がす #354
  components/molecules/EntryPoint.tsx
  components/molecules/MoAccordion/index.tsx
Labels: enhancement, develop

#359 Feature issue#358 delete mui
  components/atoms/AtInput/index.tsx
  components/atoms/EntryPoint.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/molecules/EntryPoint.tsx
  components/molecules/MoForm/index.tsx
  components/molecules/MoLabelForm/index.tsx
  components/organisms/OrAccordion/index.tsx
  components/organisms/OrCardForm/index.tsx
Labels: enhancement, develop

#364 deletebuttonの画面更新を制御 #363
  components/atoms/AtIconButton/index.tsx
Labels: bug, develop

#374 Feature issue#361 delete mui text filed
  components/atoms/AtIconButton/index.tsx
  components/atoms/AtInput/index.tsx
  components/atoms/AtLabel/index.tsx
  components/atoms/AtNoMarkLabel/index.tsx
  components/atoms/AtTextField.tsx
  components/atoms/AtTextField/index.tsx
  components/atoms/EntryPoint.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcInvalidLink.tsx
  components/ecosystems/EcLoading.tsx
  components/ecosystems/EcLp.tsx
  components/ecosystems/EcPrivacyPolicy.tsx
  components/molecules/MoAccordion/index.tsx
  components/molecules/MoFooter/index.tsx
  components/molecules/MoForm/index.tsx
  components/molecules/MoHeader/index.tsx
  components/molecules/MoLabelForm/index.tsx
  components/molecules/MoLabelTextField/index.tsx
  components/organisms/OrAccordion/index.tsx
  components/organisms/OrCardBar/index.tsx
  components/organisms/OrCardForm/index.tsx
  components/organisms/OrCardForms/index.tsx
  components/organisms/OrCardProcess/index.tsx
  components/organisms/OrCardText/index.tsx
  components/organisms/OrCardTextField/index.tsx
  components/organisms/OrVoteOptionCardForm/index.tsx
  utils/baseCss.ts
Labels: enhancement

#375 イベント作成画面のレスポンシブ #355
  architecture/hooks/ screenSize.ts
  architecture/hooks/README.md
  components/atoms/AtErrorMessage/index.tsx
  components/atoms/AtInput/index.tsx
  components/atoms/AtLabel/index.tsx
  components/atoms/AtNoMarkLabel/index.tsx
  components/atoms/EntryPoint.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/molecules/MoAccordion/index.tsx
  components/molecules/MoForm/index.tsx
  components/molecules/MoLabelForm/index.tsx
  components/organisms/OrCardForms/index.tsx
  pages/_app.tsx
  utils/baseCss.ts
Labels: enhancement

#376 dashboardのレスポンシブ対応 #336
  components/molecules/MoLabelBar/index.tsx
  components/molecules/MoLabelText/index.tsx
  components/molecules/MoLabelTextField/index.tsx
  components/organisms/OrCardProcess/index.tsx
Labels: enhancement

#380 Feature issue#379 change filename
  components/molecules/EntryPoint.tsx
  components/molecules/MoButtons/index.tsx
Labels: enhancement

#377 Feature issue#274 add storybook
  .storybook/main.js
  .storybook/manager.ts
  .storybook/preview.js
  .storybook/theme.ts
  components/atoms/AtBar/index.stories.tsx
  components/atoms/AtBar/index.tsx
  components/atoms/AtButton/index.stories.tsx
  components/atoms/AtButton/index.tsx
  components/atoms/AtErrorMessage/index.stories.tsx
  components/atoms/AtHref/index.stories.tsx
  components/atoms/AtIconButton/index.stories.tsx
  components/atoms/AtInput/index.stories.tsx
  components/atoms/AtInput/index.tsx
  components/atoms/AtLabel/index.stories.tsx
  components/atoms/AtNoMarkLabel/index.stories.tsx
  components/atoms/AtTextField/index.stories.tsx
  components/ecosystems/EcLp.tsx
  components/ecosystems/EcVoteForm.tsx
  components/molecules/MoAccordion/index.stories.tsx
  components/molecules/MoButtons.tsx
  components/molecules/MoButtons/index.stories.tsx
  components/molecules/MoButtons/index.tsx
  components/molecules/MoFooter/index.stories.tsx
  components/molecules/MoHeader/index.stories.tsx
  components/molecules/MoLabelBar/index.stories.tsx
  components/molecules/MoLabelForm/index.stories.tsx
  components/molecules/MoLabelText/index.stories.tsx
  components/molecules/MoLabelText/index.tsx
  components/molecules/MoLabelTextField/index.stories.tsx
  components/molecules/MoLabelTextField/index.tsx
  components/molecules/MoProcess/index.stories.tsx
  components/organisms/OrCardBar/index.stories.tsx
  components/organisms/OrCardBar/index.tsx
  components/organisms/OrCardForm/index.stories.tsx
  components/organisms/OrCardTextField/index.tsx
  components/organisms/OrVoteOptionCardForm/index.tsx
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#381 voteのレスポンシブ #337
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcVoteForm.tsx
  components/organisms/OrProposalBlocks/index.tsx
  components/organisms/OrVoteOptionCardForm/index.tsx
Labels: enhancement

#385 ボタンのレスポンシブ対応 #383
  components/atoms/AtButton/index.tsx
Labels: enhancement

#386 v2.5.1
  components/atoms/AtButton/index.tsx
Labels: release
