Repository quadraticvotingJP/quadratic-voting-jp, pull requests merged in 2022-04, with the labels that each got.

#100 github actions用のymlファイルを削除 #99
  .github/workflow/auto-prettier.yml
Labels: bug

#102 Feature issue#76 add chartjs
  architecture/application/setGraf.tsx
  architecture/domain/chart.ts
  components/atoms/AtBar.tsx
  components/atoms/EntryPoint.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/molecules/EntryPoint.tsx
  components/molecules/MoLabelBar.tsx
  components/organisms/EntryPoint.tsx
  components/organisms/OrCardBar.tsx
  package-lock.json
  package.json
  public/locales/ja/common.json
  types/shared.d.ts
  yarn.lock
Labels: component

#104 GrafComponentの２軸対応 #103
  architecture/application/setGraf.tsx
  architecture/domain/chart.ts
  components/ecosystems/EcDashboard.tsx
  public/locales/ja/common.json
  types/shared.d.ts
Labels: enhancement

#107 エクセルファイルダウンロード機能実装 #105
  architecture/application/downloadXlsx.tsx
  architecture/domain/chart.ts
  components/ecosystems/EcDashboard.tsx
  components/organisms/OrCardBar.tsx
  package.json
  public/locales/ja/common.json
  yarn.lock
Labels: enhancement

#108 Buttonのhover-colorの指定 #106
  components/atoms/AtButton.tsx
  components/molecules/MoButtons.tsx
Labels: enhancement

#110 日付選択のdefault値制御 #82
  components/atoms/AtInput.tsx
  components/ecosystems/EcCreateForm.tsx
  components/molecules/MoLabelForm.tsx
  components/organisms/OrCardForm.tsx
Labels: enhancement

#111 イベント作成後の遷移 #101
  architecture/adapter/setCollection.ts
  architecture/application/postEvent.ts
  architecture/domain/event.ts
  components/ecosystems/EcCreateForm.tsx
  components/organisms/OrCardForms.tsx
  package.json
  types/shared.d.ts
  yarn.lock
Labels: enhancement

#113 Loadingコンテキスト作成 #112
  components/ecosystems/EcCreateForm.tsx
  context/LoadingContext.tsx
  pages/_app.tsx
Labels: enhancement

#115 Feature issue#114 add readonly
  architecture/application/downloadXlsx.tsx
  components/atoms/AtBar.tsx
  components/atoms/AtButton.tsx
  components/atoms/AtH2.tsx
  components/atoms/AtHref.tsx
  components/atoms/AtIconButton.tsx
  components/atoms/AtInput.tsx
  components/atoms/AtInputLabel.tsx
  components/atoms/AtInputLabelNoMark.tsx
  components/atoms/AtTextField.tsx
  components/ecosystems/EcAdvertisement.tsx
  components/molecules/MoAccordion.tsx
  components/molecules/MoButtons.tsx
  components/molecules/MoForm.tsx
  components/molecules/MoLabelBar.tsx
  components/molecules/MoLabelForm.tsx
  components/molecules/MoLabelText.tsx
  components/molecules/MoLabelTextField.tsx
  components/molecules/MoProcess.tsx
  components/organisms/OrAccordion.tsx
  components/organisms/OrCardBar.tsx
  components/organisms/OrCardForm.tsx
  components/organisms/OrCardForms.tsx
  components/organisms/OrCardProcess.tsx
  components/organisms/OrCardText.tsx
  components/organisms/OrCardTextField.tsx
  types/shared.d.ts
Labels: enhancement

#117 Feature issue#77 create dashboard
  architecture/adapter/getDocument.ts
  architecture/adapter/setCollection.ts
  architecture/application/dashboardData.ts
  architecture/application/downloadTxt.tsx
  architecture/application/downloadXlsx.tsx
  architecture/application/getDashboard.ts
  architecture/application/postEvent.ts
  architecture/domain/acquiredInformation.ts
  architecture/domain/event.ts
  components/atoms/AtIconButton.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/molecules/MoLabelForm.tsx
  components/organisms/OrCardForm.tsx
  components/organisms/OrCardTextField.tsx
  package-lock.json
  package.json
  pages/dashboard/[id].tsx
  public/locales/ja/common.json
  styles/tailwind.css
  types/shared.d.ts
  yarn.lock
Labels: enhancement, component

#121 Dashboardの日付フォーム更新処理 #119
  architecture/application/dashboardData.ts
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  pages/dashboard/[id].tsx
  types/shared.d.ts
  utils/validation.ts
Labels: enhancement, component

#126 reacdmeの更新 #66
  README.md
Labels: enhancement

#133 scrollにより値の変更を阻止 #109
  components/atoms/AtInput.tsx
  components/ecosystems/EcCreateForm.tsx
  components/molecules/MoLabelForm.tsx
  components/organisms/OrCardForm.tsx
Labels: enhancement

#135 validationロジックの切り離し #130
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  utils/validation.ts
Labels: enhancement

#134 Feature issue#131 change base color
  components/atoms/AtButton.tsx
  components/atoms/AtIconButton.tsx
  components/atoms/AtInputLabel.tsx
  components/molecules/MoButtons.tsx
  components/molecules/MoFooter.tsx
  components/molecules/MoHeader.tsx
  styles/globals.css
  tailwind.config.js
Labels: enhancement

#136 お問い合わせフォームの追加 #125
  components/molecules/MoFooter.tsx
  public/locales/ja/common.json
Labels: enhancement

#137 トリガーで画面更新 #127
  components/ecosystems/EcCreateForm.tsx
Labels: bug

#138 バグが再現できないためLoading #128
  components/atoms/AtIconButton.tsx
  context/LoadingContext.tsx
  dist/404.html
  dist/index.html
Labels: enhancement

#140 iconの変更 #139
  components/atoms/AtIconButton.tsx
Labels: bug

#144 プレスフォルダーの変更 #143
  public/locales/ja/common.json
Labels: enhancement

#116 WIP! Feature issue#81 vote
  architecture/adapter/getSubDocument.ts
  architecture/adapter/setSubCollection.ts
  architecture/application/answer.ts
  architecture/application/getAnswer.ts
  architecture/application/getEvent.ts
  architecture/domain/answer.ts
  components/ecosystems/EcVoteForm.tsx
  components/ecosystems/EntryPoint.tsx
  components/organisms/EntryPoint.tsx
  components/organisms/OrProposalBlocks.tsx
  components/organisms/OrVoteOptionCardForm.tsx
  pages/vote/[id].tsx
  public/locales/ja/common.json
  types/shared.d.ts
Labels: enhancement, component

#149 lint error 解消 #148
  components/organisms/OrProposalBlocks.tsx
Labels: bug
