Repository quadraticvotingJP/quadratic-voting-jp, pull requests merged in 2022-07, with the labels that each got.

#402 Feature issue#397 update graf height
  architecture/application/dashboardData.ts
  components/atoms/AtBar/index.stories.tsx
  components/atoms/AtBar/index.tsx
  components/ecosystems/EcDashboard.tsx
  components/molecules/MoLabelBar/index.stories.tsx
  components/molecules/MoLabelBar/index.tsx
  components/organisms/OrCardBar/index.stories.tsx
  components/organisms/OrCardBar/index.tsx
  types/shared.d.ts
Labels: enhancement

#407 タイトルの変更 #406
  components/ecosystems/EcVoteForm.tsx
Labels: bug

#408 概要を補足に変換 #405
  public/locales/ja/common.json
Labels: enhancement, develop

#409 選択肢の初期表示を変更 #404
  components/ecosystems/EcCreateForm.tsx
Labels: develop

#410 日付の過去日を選択できないように修正 #263
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/molecules/MoLabelForm/index.tsx
  components/organisms/OrCardForm/index.tsx
Labels: enhancement, develop

#423 ダッシュボードのタイトルを変更 #412
  components/atoms/AtInput/index.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcVoteForm.tsx
  components/organisms/OrVoteOptionCardForm/index.tsx
  pages/_app.tsx
  public/locales/ja/common.json
Labels: bug

#424 開始時刻までの残り日時を追加
  architecture/application/getToday.ts
  architecture/application/useInterval.ts
  components/ecosystems/EcTimeReflection.tsx
  components/ecosystems/EntryPoint.tsx
  pages/vote/[id].tsx
  public/locales/ja/common.json
Labels: develop

#426 v3.0.0
  architecture/application/dashboardData.ts
  architecture/application/getToday.ts
  architecture/application/useInterval.ts
  components/atoms/AtBar/index.stories.tsx
  components/atoms/AtBar/index.tsx
  components/atoms/AtInput/index.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcTimeReflection.tsx
  components/ecosystems/EcVoteForm.tsx
  components/ecosystems/EntryPoint.tsx
  components/molecules/MoLabelBar/index.stories.tsx
  components/molecules/MoLabelBar/index.tsx
  components/molecules/MoLabelForm/index.tsx
  components/organisms/OrCardBar/index.stories.tsx
  components/organisms/OrCardBar/index.tsx
  components/organisms/OrCardForm/index.tsx
  components/organisms/OrVoteOptionCardForm/index.tsx
  package.json
  pages/_app.tsx
  pages/vote/[id].tsx
  public/locales/ja/common.json
  types/shared.d.ts
  yarn.lock
Labels: develop

#428 v3.0.0
  architecture/application/dashboardData.ts
  architecture/application/getToday.ts
  architecture/application/useInterval.ts
  components/atoms/AtBar/index.stories.tsx
  components/atoms/AtBar/index.tsx
  components/atoms/AtInput/index.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcTimeReflection.tsx
  components/ecosystems/EcVoteForm.tsx
  components/ecosystems/EntryPoint.tsx
  components/molecules/MoLabelBar/index.stories.tsx
  components/molecules/MoLabelBar/index.tsx
  components/molecules/MoLabelForm/index.tsx
  components/organisms/OrCardBar/index.stories.tsx
  components/organisms/OrCardBar/index.tsx
  components/organisms/OrCardForm/index.tsx
  components/organisms/OrVoteOptionCardForm/index.tsx
  package.json
  pages/_app.tsx
  pages/vote/[id].tsx
  public/locales/ja/common.json
  types/shared.d.ts
  yarn.lock
Labels: main

#430 ページタイトルのbottom調整 #429
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcTimeReflection.tsx
  components/ecosystems/EcVoteForm.tsx
  components/shared/EntryPoint.tsx
  components/shared/H2/index.ts
Labels: enhancement

#432 投票画面のクレジット数の表示を変更 #431
  components/organisms/OrVoteOptionCardForm/index.tsx
Labels: enhancement

#434 v3.1.0
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcTimeReflection.tsx
  components/ecosystems/EcVoteForm.tsx
  components/organisms/OrVoteOptionCardForm/index.tsx
  components/shared/EntryPoint.tsx
  components/shared/H2/index.ts
Labels: main

#440 クレジットの最大を100から99に変更 #439
  components/ecosystems/EcCreateForm.tsx
  public/locales/ja/common.json
  utils/validation.ts
Labels: enhancement

#443 v3.2.0
  components/ecosystems/EcCreateForm.tsx
  components/organisms/OrProposalBlocks/index.tsx
  public/locales/ja/common.json
  utils/validation.ts
Labels: enhancement

#444 v3.2.0
  components/ecosystems/EcCreateForm.tsx
  components/organisms/OrProposalBlocks/index.tsx
  public/locales/ja/common.json
  utils/validation.ts
Labels: main

#447 Feature issue#445 update overview
  components/molecules/MoAccordion/index.tsx
  components/molecules/MoLabelText/index.tsx
  components/organisms/OrVoteOptionCardForm/index.tsx
Labels: enhancement

#449 Feature issue#448 change crad
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcVoteForm.tsx
  components/organisms/EntryPoint.tsx
  components/organisms/OrCard/index.tsx
  components/organisms/OrCardBar/index.stories.tsx
  components/organisms/OrCardBar/index.tsx
  components/organisms/OrCardForm/index.stories.tsx
  components/organisms/OrCardForm/index.tsx
  components/organisms/OrCardForms/index.tsx
  components/organisms/OrCardProcess/index.tsx
  components/organisms/OrCardText/index.tsx
  components/organisms/OrCardTextField/index.tsx
Labels: enhancement

#453 Feature issue#452 change lp text
  components/atoms/AtButton/index.tsx
  components/ecosystems/EcLp.tsx
  components/molecules/MoHeader/index.tsx
  pages/_app.tsx
  pages/create/index.tsx
  pages/dashboard/[id].tsx
  pages/index.tsx
  pages/privacypolicy/index.tsx
  pages/termsofservice/index.tsx
  pages/vote/[id].tsx
  public/locales/ja/common.json
  styles/globals.css
  utils/baseCss.ts
Labels: enhancement

#454 v3.3.0
  components/atoms/AtButton/index.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcLp.tsx
  components/ecosystems/EcVoteForm.tsx
  components/molecules/MoAccordion/index.tsx
  components/molecules/MoHeader/index.tsx
  components/molecules/MoLabelText/index.tsx
  components/organisms/EntryPoint.tsx
  components/organisms/OrCard/index.tsx
  components/organisms/OrCardBar/index.stories.tsx
  components/organisms/OrCardBar/index.tsx
  components/organisms/OrCardForm/index.stories.tsx
  components/organisms/OrCardForm/index.tsx
  components/organisms/OrCardForms/index.tsx
  components/organisms/OrCardProcess/index.tsx
  components/organisms/OrCardText/index.tsx
  components/organisms/OrCardTextField/index.tsx
  components/organisms/OrVoteOptionCardForm/index.tsx
  pages/_app.tsx
  pages/create/index.tsx
  pages/dashboard/[id].tsx
  pages/index.tsx
  pages/privacypolicy/index.tsx
  pages/termsofservice/index.tsx
  pages/vote/[id].tsx
  public/locales/ja/common.json
  styles/globals.css
  utils/baseCss.ts
Labels: enhancement

#455 v3.3.0
  components/atoms/AtButton/index.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcLp.tsx
  components/ecosystems/EcVoteForm.tsx
  components/molecules/MoAccordion/index.tsx
  components/molecules/MoHeader/index.tsx
  components/molecules/MoLabelText/index.tsx
  components/organisms/EntryPoint.tsx
  components/organisms/OrCard/index.tsx
  components/organisms/OrCardBar/index.stories.tsx
  components/organisms/OrCardBar/index.tsx
  components/organisms/OrCardForm/index.stories.tsx
  components/organisms/OrCardForm/index.tsx
  components/organisms/OrCardForms/index.tsx
  components/organisms/OrCardProcess/index.tsx
  components/organisms/OrCardText/index.tsx
  components/organisms/OrCardTextField/index.tsx
  components/organisms/OrVoteOptionCardForm/index.tsx
  pages/_app.tsx
  pages/create/index.tsx
  pages/dashboard/[id].tsx
  pages/index.tsx
  pages/privacypolicy/index.tsx
  pages/termsofservice/index.tsx
  pages/vote/[id].tsx
  public/locales/ja/common.json
  styles/globals.css
  utils/baseCss.ts
Labels: main

#457 テーマカラーの設定 #456
  pages/_document.tsx
Labels: enhancement

#458 v3.4.0
  pages/_document.tsx
Labels: enhancement

#459 v3.4.0
  pages/_document.tsx
Labels: enhancement

#464 Feature issue#462 pc lp
  components/ecosystems/EcLp.tsx
  public/locales/ja/common.json
  utils/baseCss.ts
Labels: enhancement

#465 v.3.5.0
  components/ecosystems/EcLp.tsx
  public/locales/ja/common.json
  utils/baseCss.ts
Labels: develop

#466 v3.5.0
  components/ecosystems/EcLp.tsx
  public/locales/ja/common.json
  utils/baseCss.ts
Labels: enhancement

#468 広告の設置 #467
  components/ecosystems/EcDashboard.tsx
Labels: enhancement

#469 v4.0.0
  components/ecosystems/EcDashboard.tsx
Labels: enhancement

#470 v4.0.0
  components/ecosystems/EcDashboard.tsx
Labels: main

#473 oprnGraphの設置 #471
  lib/next-seo.config.ts
Labels: develop

#479 投票画面にルールリンクの追加 #472
  components/ecosystems/EcVoteForm.tsx
  public/locales/ja/common.json
Labels: enhancement

#480 ヘッダーのリストをコメントアウト #478
  components/molecules/MoHeader/index.tsx
Labels: enhancement

#481 票数を99票に固定 #475
  components/ecosystems/EcCreateForm.tsx
  public/locales/ja/common.json
Labels: enhancement, must, develop

#482 v4.1.0
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcVoteForm.tsx
  components/molecules/MoHeader/index.tsx
  lib/next-seo.config.ts
  public/locales/ja/common.json
Labels: release

#483 v4.1.0
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcVoteForm.tsx
  components/molecules/MoHeader/index.tsx
  lib/next-seo.config.ts
  public/locales/ja/common.json
Labels: enhancement, main

#486 投票リンクを一本化 #175
  architecture/application/dashboardData.ts
  architecture/application/postEvent.ts
  architecture/domain/event.ts
  components/atoms/AtTextField/index.stories.tsx
  components/atoms/AtTextField/index.tsx
  components/atoms/EntryPoint.tsx
  components/ecosystems/EcDashboard.tsx
  components/molecules/EntryPoint.tsx
  components/molecules/MoLabelTextField/index.stories.tsx
  components/molecules/MoLabelTextField/index.tsx
  types/shared.d.ts
Labels: must, develop

#487 v4.2.0
  architecture/application/dashboardData.ts
  architecture/application/postEvent.ts
  architecture/domain/event.ts
  components/atoms/AtTextField/index.stories.tsx
  components/atoms/AtTextField/index.tsx
  components/atoms/EntryPoint.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcVoteForm.tsx
  components/molecules/EntryPoint.tsx
  components/molecules/MoLabelTextField/index.stories.tsx
  components/molecules/MoLabelTextField/index.tsx
  pages/vote/[id].tsx
  types/shared.d.ts
Labels: develop

#488 v4.2.0
  architecture/application/dashboardData.ts
  architecture/application/postEvent.ts
  architecture/domain/event.ts
  components/atoms/AtTextField/index.stories.tsx
  components/atoms/AtTextField/index.tsx
  components/atoms/EntryPoint.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcVoteForm.tsx
  components/molecules/EntryPoint.tsx
  components/molecules/MoLabelTextField/index.stories.tsx
  components/molecules/MoLabelTextField/index.tsx
  pages/vote/[id].tsx
  types/shared.d.ts
Labels: main

#491 テキストの修正 #490
  public/locales/ja/common.json
Labels: enhancement

#492 テキストの修正 #490
  public/locales/ja/common.json
Labels: enhancement

#493 Twitterのリンクをフッターに設定 #489
  components/molecules/MoFooter/index.tsx
  public/locales/ja/common.json
Labels: enhancement

#494 SP版のLPを修正 #463
  components/ecosystems/EcLp.tsx
  public/locales/ja/common.json
Labels: enhancement

#495 v4.3.0
  components/ecosystems/EcLp.tsx
  components/molecules/MoFooter/index.tsx
  public/locales/ja/common.json
Labels: enhancement

#496 v4.3.0
  components/ecosystems/EcLp.tsx
  components/molecules/MoFooter/index.tsx
  public/locales/ja/common.json
Labels: main

#499 Feature issue#489 create modal
  components/atoms/AtButton/index.tsx
  components/ecosystems/EcVoteForm.tsx
  components/organisms/EntryPoint.tsx
  components/organisms/OrModal/container.tsx
  components/organisms/OrModal/index.stories.tsx
  components/organisms/OrModal/presentation.tsx
Labels: enhancement

#500 v4.4.0
  components/atoms/AtButton/index.tsx
  components/ecosystems/EcVoteForm.tsx
  components/organisms/EntryPoint.tsx
  components/organisms/OrModal/container.tsx
  components/organisms/OrModal/index.stories.tsx
  components/organisms/OrModal/presentation.tsx
Labels: develop

#501 v4.4.0
  components/atoms/AtButton/index.tsx
  components/ecosystems/EcVoteForm.tsx
  components/organisms/EntryPoint.tsx
  components/organisms/OrModal/container.tsx
  components/organisms/OrModal/index.stories.tsx
  components/organisms/OrModal/presentation.tsx
Labels: main
