Repository quadraticvotingJP/quadratic-voting-jp, pull requests merged in 2022-08, with the labels that each got.

#505 Feature issue#503 change option form
  architecture/domain/event.ts
  components/ecosystems/EcCreateForm.tsx
  components/molecules/MoAccordion/index.stories.tsx
  components/molecules/MoAccordion/index.tsx
  components/organisms/EntryPoint.tsx
  components/organisms/OrAccordion/index.tsx
  components/organisms/OrCard/index.tsx
  components/organisms/OrOptionForms/index.tsx
  public/locales/ja/common.json
  types/shared.d.ts
Labels: enhancement

#506 v4.5.0
  __tests__/pages/index.test.tsx
  architecture/domain/event.ts
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcLp.tsx
  components/molecules/MoAccordion/index.stories.tsx
  components/molecules/MoAccordion/index.tsx
  components/organisms/EntryPoint.tsx
  components/organisms/OrAccordion/index.tsx
  components/organisms/OrCard/index.tsx
  components/organisms/OrOptionForms/index.tsx
  jest.config.js
  package-lock.json
  package.json
  pages/index.tsx
  public/locales/ja/common.json
  types/shared.d.ts
  utils/testUtils.tsx
  yarn.lock
Labels: develop

#507 v4.5.0
  __tests__/pages/index.test.tsx
  architecture/domain/event.ts
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcLp.tsx
  components/molecules/MoAccordion/index.stories.tsx
  components/molecules/MoAccordion/index.tsx
  components/organisms/EntryPoint.tsx
  components/organisms/OrAccordion/index.tsx
  components/organisms/OrCard/index.tsx
  components/organisms/OrOptionForms/index.tsx
  jest.config.js
  package-lock.json
  package.json
  pages/index.tsx
  public/locales/ja/common.json
  types/shared.d.ts
  utils/testUtils.tsx
  yarn.lock
Labels: main

#510 イベント作成ボタンの作成 #502
  components/molecules/MoHeader/index.tsx
  public/locales/ja/common.json
Labels: enhancement

#511 Lpの文言修正 #509
  public/locales/ja/common.json
Labels: enhancement

#513 Feature issue#512 change modal text
  components/ecosystems/EcVoteForm.tsx
Labels: enhancement

#514 選択肢一覧のカードの表示 #508
  architecture/application/voteData.ts
  components/ecosystems/EcVoteForm.tsx
  public/locales/ja/common.json
  types/shared.d.ts
Labels: enhancement

#515 v4.6.0
  architecture/application/voteData.ts
  components/ecosystems/EcVoteForm.tsx
  components/molecules/MoHeader/index.tsx
  public/locales/ja/common.json
  types/shared.d.ts
Labels: enhancement

#516 v4.6.0
  architecture/application/voteData.ts
  components/ecosystems/EcVoteForm.tsx
  components/molecules/MoHeader/index.tsx
  public/locales/ja/common.json
  types/shared.d.ts
Labels: main

#519 Feature issue#463 style change lp
  components/atoms/AtImage/index.tsx
  components/ecosystems/EcLp.tsx
  public/locales/ja/common.json
Labels: enhancement

#520 v4.7.0
  components/atoms/AtImage/index.tsx
  components/ecosystems/EcLp.tsx
  public/locales/ja/common.json
Labels: develop

#521 v4.7.0
  components/atoms/AtImage/index.tsx
  components/ecosystems/EcLp.tsx
  public/locales/ja/common.json
Labels: main

#524 QVのseoを再セット #518
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcLp.tsx
  components/ecosystems/EcPrivacyPolicy.tsx
  components/ecosystems/EcTermsOfService.tsx
  components/ecosystems/EcVoteForm.tsx
  components/shared/EntryPoint.tsx
  components/shared/H1/index.ts
  lib/next-seo.config.ts
  pages/create/index.tsx
  pages/dashboard/[id].tsx
  pages/index.tsx
  pages/privacypolicy/index.tsx
  pages/termsofservice/index.tsx
  pages/vote/[id].tsx
Labels: enhancement

#525 v4.8.0
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcLp.tsx
  components/ecosystems/EcPrivacyPolicy.tsx
  components/ecosystems/EcTermsOfService.tsx
  components/ecosystems/EcVoteForm.tsx
  components/shared/EntryPoint.tsx
  components/shared/H1/index.ts
  lib/next-seo.config.ts
  pages/create/index.tsx
  pages/dashboard/[id].tsx
  pages/index.tsx
  pages/privacypolicy/index.tsx
  pages/termsofservice/index.tsx
  pages/vote/[id].tsx
Labels: develop

#526 v4.8.0
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcLp.tsx
  components/ecosystems/EcPrivacyPolicy.tsx
  components/ecosystems/EcTermsOfService.tsx
  components/ecosystems/EcVoteForm.tsx
  components/shared/EntryPoint.tsx
  components/shared/H1/index.ts
  lib/next-seo.config.ts
  pages/create/index.tsx
  pages/dashboard/[id].tsx
  pages/index.tsx
  pages/privacypolicy/index.tsx
  pages/termsofservice/index.tsx
  pages/vote/[id].tsx
Labels: main

#528 Feature issue#527 change seo description
  lib/next-seo.config.ts
  pages/create/index.tsx
  pages/dashboard/[id].tsx
  pages/privacypolicy/index.tsx
  pages/termsofservice/index.tsx
  pages/vote/[id].tsx
Labels: enhancement

#529 v.4.9.0
  lib/next-seo.config.ts
  pages/create/index.tsx
  pages/dashboard/[id].tsx
  pages/privacypolicy/index.tsx
  pages/termsofservice/index.tsx
  pages/vote/[id].tsx
Labels: develop

#530 v4.9.0
  lib/next-seo.config.ts
  pages/create/index.tsx
  pages/dashboard/[id].tsx
  pages/privacypolicy/index.tsx
  pages/termsofservice/index.tsx
  pages/vote/[id].tsx
Labels: main

#532 visitイベントの設置 #531
  architecture/application/gaLogEvent.ts
  architecture/domain/gaEventName.ts
  components/ecosystems/EcLp.tsx
  firebase/initialize.js
  pages/create/index.tsx
  pages/dashboard/[id].tsx
  pages/index.tsx
  pages/privacypolicy/index.tsx
  pages/termsofservice/index.tsx
  pages/vote/[id].tsx
Labels: enhancement

#533 v4.10.0
  architecture/application/gaLogEvent.ts
  architecture/domain/gaEventName.ts
  components/ecosystems/EcLp.tsx
  firebase/initialize.js
  pages/create/index.tsx
  pages/dashboard/[id].tsx
  pages/index.tsx
  pages/privacypolicy/index.tsx
  pages/termsofservice/index.tsx
  pages/vote/[id].tsx
Labels: enhancement

#534 v4.10.0
  architecture/application/gaLogEvent.ts
  architecture/domain/gaEventName.ts
  components/ecosystems/EcLp.tsx
  firebase/initialize.js
  pages/create/index.tsx
  pages/dashboard/[id].tsx
  pages/index.tsx
  pages/privacypolicy/index.tsx
  pages/termsofservice/index.tsx
  pages/vote/[id].tsx
Labels: enhancement

#535 イベントの設定 #531
  architecture/domain/gaEventName.ts
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcVoteForm.tsx
Labels: enhancement

#536 v4.11.0
  architecture/domain/gaEventName.ts
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcVoteForm.tsx
Labels: enhancement, develop

#537 v4.11.0
  architecture/domain/gaEventName.ts
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EcVoteForm.tsx
Labels: main

#539 seoの追加 #538
  architecture/domain/gaEventName.ts
  components/ecosystems/EcVoteForm.tsx
  components/molecules/MoFooter/index.tsx
  components/molecules/MoHeader/index.tsx
Labels: enhancement

#540 v4.12.0
  architecture/domain/gaEventName.ts
  components/ecosystems/EcVoteForm.tsx
  components/molecules/MoFooter/index.tsx
  components/molecules/MoHeader/index.tsx
Labels: develop

#541 v4.12.0
  architecture/domain/gaEventName.ts
  components/ecosystems/EcVoteForm.tsx
  components/molecules/MoFooter/index.tsx
  components/molecules/MoHeader/index.tsx
Labels: main

#544 v4.13.0
  components/ecosystems/EcAdSense.tsx
  pages/_app.tsx
  pages/_document.tsx
  types/window.d.ts
Labels: develop

#545 v.4.13.0
  components/ecosystems/EcAdSense.tsx
  pages/_app.tsx
  pages/_document.tsx
  types/window.d.ts
Labels: main

#547 Feature issue#546 delete pressfolder
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcLp.tsx
  components/organisms/OrOptionForms/index.tsx
  public/locales/ja/common.json
Labels: enhancement, develop

#548 v4.14.0
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcLp.tsx
  components/organisms/OrOptionForms/index.tsx
  public/locales/ja/common.json
Labels: develop

#549 v4.14.0
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcLp.tsx
  components/organisms/OrOptionForms/index.tsx
  public/locales/ja/common.json
Labels: main

#551 Clarityの導入 #550
  pages/_document.tsx
Labels: enhancement

#552 v4.15.0
  pages/_document.tsx
Labels: develop

#553 v4.15.0
  pages/_document.tsx
Labels: main

#555 noindexの付与 #554
  pages/create/index.tsx
  pages/dashboard/[id].tsx
  pages/vote/[id].tsx
Labels: enhancement

#557 v4.16.0
  pages/create/index.tsx
  pages/dashboard/[id].tsx
  pages/vote/[id].tsx
Labels: main

#564 Feature issue#562 rename dashboard title
  components/ecosystems/EcDashboard.tsx
  public/locales/ja/common.json
Labels: enhancement

#565 投票モーダルにAlertテキストを追加 #563
  components/ecosystems/EcVoteForm.tsx
Labels: enhancement

#566 コピーアイコンの追加 #559
  components/atoms/AtIconButton/index.tsx
  components/ecosystems/EcDashboard.tsx
  components/molecules/MoLabelForm/index.tsx
  pages/dashboard/[id].tsx
  pages/vote/[id].tsx
Labels: enhancement
