Repository quadraticvotingJP/quadratic-voting-jp, pull requests merged in 2022-03, with the labels that each got.

#4 tailwindの導入
  package.json
  pages/_app.tsx
  pages/index.tsx
  postcss.config.js
  styles/Home.module.css
  styles/globals.css
  styles/tailwind.css
  tailwind.config.js
  yarn.lock
Labels: enhancement

#8 ポート番号の変更 #7
  README.md
  package.json
Labels: enhancement

#9 directoryの変更とREADMEの追加 #6
  architecture/README.md
  architecture/adapter/README.md
  architecture/application/README.md
  architecture/domain/README.md
  components/README.md
  components/atoms/README.md
  components/ecosystems/README.md
  components/molecules/README.md
  components/organisms/README.md
  pages/README.md
  types/README.md
Labels: enhancement

#16 rootから相対パスでimportできるようにする #15
  components/atoms/At.tsx
  tsconfig.json
Labels: enhancement

#18 MUIのVersionUpdate #17
  components/atoms/At.tsx
  package.json
  pages/index.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement

#19 ボタンcomponent作成 #12
  components/atoms/AtButton.tsx
Labels: enhancement

#20 feature/#11 i18n install
  next-i18next.config.js
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  public/locales/ja/common.json
  yarn.lock
Labels: enhancement

#22 index.tsxからの切り離し #21
  pages/PaTop.tsx
  pages/index.tsx
  public/locales/ja/common.json
Labels: enhancement

#28 ラベル作成 #14
  components/atoms/AtInputLabel.tsx
  pages/PaTop.tsx
  styles/globals.css
Labels: enhancement, component

#29 タイトルコンポーネント作成 #27
  components/atoms/AtH2.tsx
  pages/PaTop.tsx
Labels: enhancement, component

#31 Atagの設置 #30
  components/atoms/AtAtag.tsx
  pages/PaTop.tsx
  public/locales/ja/common.json
Labels: enhancement, component

#33 react-hool-formの導入 #32
  package.json
  yarn.lock
Labels: enhancement

#34 フォームコンポーネント作成 #13
  components/atoms/AtInput.tsx
  pages/PaTop.tsx
  types/shared.d.ts
Labels: enhancement, component

#35 Feature issue#25 create form
  components/atoms/AtInput.tsx
  components/atoms/AtInputLabel.tsx
  components/molecules/MoForm.tsx
  pages/PaTop.tsx
Labels: enhancement, component

#36 カード付きフォームの作成 #26
  components/molecules/MoForm.tsx
  components/organisms/OrForm.tsx
  pages/PaTop.tsx
Labels: enhancement, component

#37 ヘッダーの作成 #23
  components/atoms/AtAtag.tsx
  components/molecules/MoHeader.tsx
  pages/PaTop.tsx
  pages/index.tsx
  public/locales/ja/common.json
Labels: enhancement, component

#39 フッターの作成 #24
  components/molecules/MoFooter.tsx
  components/molecules/MoHeader.tsx
  pages/index.tsx
Labels: enhancement, component

#40 要素だけ配置 #38
  components/atoms/AtButton.tsx
  components/ecosystems/EcAdvertisement.tsx
  components/ecosystems/EcExplanation.tsx
  pages/PaTop.tsx
  public/locales/ja/common.json
Labels: enhancement, component

#42 エントリポイントの追加 #41
  components/README.md
  components/atoms/AtAtag.tsx
  components/atoms/AtButton.tsx
  components/atoms/AtH2.tsx
  components/atoms/AtInput.tsx
  components/atoms/AtInputLabel.tsx
  components/atoms/EntryPoint.tsx
  components/atoms/README.md
  components/ecosystems/EcAdvertisement.tsx
  components/ecosystems/EcExplanation.tsx
  components/ecosystems/EntryPoint.tsx
  components/ecosystems/README.md
  components/molecules/EntryPoint.tsx
  components/molecules/MoFooter.tsx
  components/molecules/MoForm.tsx
  components/molecules/MoHeader.tsx
  components/molecules/README.md
  components/organisms/EntryPoint.tsx
  components/organisms/OrForm.tsx
  pages/PaTop.tsx
  pages/index.tsx
Labels: enhancement

#45 ヘッダー・フッターの固定を解除 44#
  components/ecosystems/EcExplanation.tsx
  components/molecules/MoFooter.tsx
Labels: enhancement

#49 コメントアウトの削除 #47
  components/ecosystems/EcExplanation.tsx
  components/molecules/MoFooter.tsx
  pages/PaTop.tsx
  pages/index.tsx
Labels: enhancement

#50 firebsaeの導入 #10
  .firebaserc
  dist/404.html
  dist/index.html
  firebase.json
  firebase/initialize.ts
  firestore.indexes.json
  firestore.rules
  functions/.eslintrc.js
  functions/.gitignore
  functions/package-lock.json
  functions/package.json
  functions/src/index.ts
  functions/tsconfig.dev.json
  functions/tsconfig.json
Labels: enhancement

#52 gitignoreの変更 #51
  .gitignore
Labels: enhancement

#58 ルーティングの検知 #55
  architecture/application/routing.tsx
  components/atoms/AtButton.tsx
  components/ecosystems/EcExplanation.tsx
  pages/_app.tsx
Labels: enhancement

#59 フッターの仕様を変更 #57
  components/molecules/MoFooter.tsx
Labels: enhancement

#61 create form製造 #60
  components/atoms/AtButton.tsx
  components/atoms/AtIconButton.tsx
  components/atoms/AtInput.tsx
  components/atoms/AtInputLabelNoMark.tsx
  components/atoms/EntryPoint.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EntryPoint.tsx
  components/molecules/EntryPoint.tsx
  components/molecules/MoAccordion.tsx
  components/molecules/MoForm.tsx
  components/molecules/MoLabelForm.tsx
  components/organisms/EntryPoint.tsx
  components/organisms/OrAccordion.tsx
  components/organisms/OrForm.tsx
  components/organisms/OrForms.tsx
  firebase/initialize.js
  package.json
  pages/create/index.tsx
  public/locales/ja/common.json
  types/shared.d.ts
  utils/validation.ts
  yarn.lock
Labels: enhancement

#63 footerにgithubのリンクを追加 #61
  components/molecules/MoFooter.tsx
  public/locales/ja/common.json
Labels: enhancement

#67 Buttonのcolorを変更 #56
  components/atoms/AtButton.tsx
Labels: enhancement

#69 linterrorの解消 #69
  components/ecosystems/EcCreateForm.tsx
Labels: bug

#71 リンクタグの差し替え #70
  components/atoms/AtAtag.tsx
  components/atoms/AtHref.tsx
  components/atoms/EntryPoint.tsx
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcExplanation.tsx
  components/molecules/MoAccordion.tsx
  components/molecules/MoFooter.tsx
  components/molecules/MoHeader.tsx
Labels: component

#72 Feature issue#46 auth
  firebase.json
  firebase/initialize.js
  package.json
  pages/_app.tsx
  public/404.html
  public/index.html
  yarn.lock
Labels: enhancement

#86 イベント作成APIの疎通 #73
  architecture/adapter/setCollection.ts
  architecture/application/postEvent.ts
  architecture/domain/event.ts
  components/ecosystems/EcCreateForm.tsx
  firebase/initialize.js
  pages/_app.tsx
  types/shared.d.ts
Labels: enhancement

#87 ラベル付きテキストカードの作成 #75
  components/ecosystems/EcCreateForm.tsx
  components/ecosystems/EcDashboard.tsx
  components/ecosystems/EntryPoint.tsx
  components/molecules/EntryPoint.tsx
  components/molecules/MoLabelText.tsx
  components/organisms/EntryPoint.tsx
  components/organisms/OrCardForm.tsx
  components/organisms/OrCardForms.tsx
  components/organisms/OrCardText.tsx
  pages/dashboard/[id].tsx
  public/locales/ja/common.json
Labels: component

#88 編集Buttonの追加 #75
  components/ecosystems/EcDashboard.tsx
  components/molecules/MoLabelText.tsx
  components/organisms/OrCardText.tsx
Labels: component

#89 選択Buttonの作成 #78
  components/ecosystems/EcDashboard.tsx
  components/molecules/EntryPoint.tsx
  components/molecules/MoButtons.tsx
Labels: component

#90 投票過程Componentの作成 #74
  components/atoms/AtH2.tsx
  components/ecosystems/EcDashboard.tsx
  components/molecules/EntryPoint.tsx
  components/molecules/MoProcess.tsx
  components/organisms/EntryPoint.tsx
  components/organisms/OrCardProcess.tsx
  public/locales/ja/common.json
Labels: component

#92 読み取り専用フォームの作成 #91
  components/atoms/AtInput.tsx
  components/ecosystems/EcDashboard.tsx
  components/molecules/MoLabelForm.tsx
  components/organisms/OrCardForm.tsx
  public/locales/ja/common.json
Labels: component

#94 textfieldの作成 #93
  components/atoms/AtTextField.tsx
  components/atoms/EntryPoint.tsx
  components/ecosystems/EcDashboard.tsx
  components/molecules/EntryPoint.tsx
  components/molecules/MoButtons.tsx
  components/molecules/MoLabelTextField.tsx
  components/organisms/EntryPoint.tsx
  components/organisms/OrCardProcess.tsx
  components/organisms/OrCardTextField.tsx
  pages/vote/[id].tsx
  public/locales/ja/common.json
Labels: component

#97 ymlファイルにアクション内容を記述 #95
  .github/workflow/auto-prettier.yml
  package.json
  yarn.lock
Labels: enhancement
